### ISSUE TITLE
Export a large number of documents as a CSV file

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/marklogic-spring-batch#119]
As a developer
I want to TITLE
So that I can run export out a csv file without timing out the HTTP request.

One common batch processing use case is exporting out CSV files from MarkLogic.  The constraint is usually needing to export out a CSV file in a single HTTP request.  Therefore I am imposing a HTTP time limit on my batch processing job that is unnecessary.  

Implementation Details
I want to run a long running batch process where I issue multiple HTTP GET /search requests.  I wan to call /search to utilize the pagination capability.  Each search request will use the transform parameter to transform the results to a CSV file.  These results will be STREAMED out to a CSV file written to disk.

**Comment by rjrudin** [comment]
corb2 does this well - worth checking out their code to see how they write to a File. If there's a single Writer, that can open a FileOutputStream in the open() method of an ItemStreamWriter and then close it in the close() method. Gets trickier with a thread pool of writers, though we haven't addressed that. And I'm not sure what would happen if Spring Batch used a thread pool as well, that probably wouldn't work well.

**Comment by hansenmc** [comment]
CoRB2 does this in the ExportBatchToFileTask.writeToFile(), which synchronizes the code block performing the write operation
https://github.com/marklogic/corb2/blob/master/src/main/java/com/marklogic/developer/corb/ExportBatchToFileTask.java#L68

**Comment by sastafford** [comment]
This issue is being transferred to the [hector](https://github.com/sastafford/hector) project.
