### ISSUE TITLE
Resume paused or failed job

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/marklogic-spring-batch#136]
As an administrator I want to be able to pickup where a paused or failed job left off without losing any data or repeating more work than necessary. This would apply to ingest, export, and transformation jobs. A failure might occur in the client (JVM) or on the server. An implementation should assume multiple concurrent  batch operations, with one transaction per batch.

**Comment by sastafford** [comment]
I think we start with using an existing job and building in some restart capability into the JobConfig.  This will require persisting some extra pointer information in the Job execution context.

**Comment by sastafford** [comment]
The scope of this task is to create a sample JobConfig in the samples project that demonstrates restart capability.  It doesn't necessarily have to use MarkLogic.

**Comment by sastafford** [comment]
Moving this to the cookbook

https://github.com/sastafford/spring-batch-cookbook/issues
