### ISSUE TITLE
Main is closing application context too soon

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-spring-batch#147]
This only happens if you use the MarkLogicJobExecutionDao to store jobs in MarkLogic.

But in Main.java

``` java
        else {
            ConfigurableApplicationContext ctx = buildApplicationContext(options);
            JobParameters params = buildJobParameters(options);
            JobLauncher launcher = getJobLauncher(ctx);
            Job job = getJobToExecute(ctx, options);
            try {
                return launcher.run(job, params);
            } finally {
                ctx.close();
            }
        }
```

the call to ctx.close() forces all the beans to go away. This includes the BatchDatabaseClientProvider which then tells the underlying DatabaseClientManager to destroy itself:

BatchDatabaseClientProvider.java:

``` java
    @Override
    public void destroy() throws Exception {
        if (manager != null) {
            manager.destroy();
        }
    }
```

Then, after the job is finished, Spring Batch tells the MarkLogicJobExecutionDao to update the job in the MarkLogic. When it tries, BOOM! The connection is already released and it gets very upset.

A simple fix is to not call ctx.close(). I did this in the Data Hub Framework where I run a job manually (not via Main).

But I'm wondering if that is the correct solution.

**Comment by sastafford** [comment]
@paxtonhare - I'm trying to reproduce but I have a couple of questions.  

Is this for a long ingest job? 

Are you storing Job metadata in a different database than your content database?  Or is it in the same database?

**Comment by paxtonhare** [comment]
@sastafford, sorry for the delay in responding. It's a separate database.
And job runtime doesn't matter. It's simply a matter of beans being cleaned
up before the last job status update is written.

On Fri, Sep 23, 2016 at 3:47 PM, Scott A. Stafford <notifications@github.com

**Comment by sastafford** [comment]
This bug is OBE.  I'm deprecating use of the Main program in favor for the OOTB CommandLineJobRunner.
