### ISSUE TITLE
Research performance of writing data to MarkLogicJobRepository

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/marklogic-spring-batch#208]

**Comment by damonfeldman** [comment]
This task is identified for Esme to use to ramp on, extend and review MSB

- We think the job repository needs performance tuning 
   - For long-running jobs, the repository may perform poorly
   - A likely reason is that it is writing to the Job Repository too often
   - One possible solution is to cache job status in memory, then write to MarkLogic
      - However, a big function of the Job repository is to allow a job to re-start after a pause or failure, so we need to be sure that we do not allow the repository to get into a state that is inconsistent with the work actually done, or will cause duplicate or incorrect data on restart
- Functionally, the Job Repository works now
- A code review of the Job Repository fits with a larger epic/task of reviewing all the MSB code

**Comment by sastafford** [comment]
The output of this task will be opening up additional tickets that would be code fixes to improve write performance to the JobRepository.

**Comment by sastafford** [comment]
Closing this ticket.  I refactored how data is written to the MarkLogic Job Repository that I think speeds things up a bit.  The fact is that when you enable to MarkLogicJobRepository, you are going to introduce some performance overhead.  This overhead may be acceptable for the benefits of persisting job metadata.  Please note that the overhead of writing to the JobRepo gets worse for smaller chunk sizes.  The bottom line is that if you are using the MarkLogicJobRepo, then the chunk size should not be a small number .
