### ISSUE TITLE
Run performance benchmarks between MLCP and SB

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/marklogic-spring-batch#243]

**Comment by jmakeig** [comment]
I’m definitely interested in what you find.

**Comment by sastafford** [comment]
Program | Time (sec) | Time (min) | Chunk | Threads | Documents | JobRepo On?
-- | -- | -- | -- | -- | -- | --
mlcp | 1150 | 19.2 | 200 | 4 | 3594149 |  
batch | 2436 | 40.6 | 200 | 4 | 3594149 |  
batch | 1250 | 20.8 | 500 | 4 | 3594149 | No
batch | 1355 | 22.6 | 500 | 4 | 3594149 | Yes
batch | 1360 | 22.7 | 500 | 8 | 3594149 | No
batch | 1296 | 21.6 | 1000 | 4 | 3594149 | No
