### ISSUE TITLE
Recursively traverse a directory for files

### ISSUE THREAD

**Issue by sastafford** [marklogic-community/marklogic-spring-batch#244]
As a developer
I want the EnhancedResourcesItemReader to "Recursively traverse a directory to read in files"
So that I can read all the subfolders under a directory. 

Note that this should be the default behavior for this ItemReader.  

Need to modify the EnhancedResourcesItemReader to recursively traverse a directory of files.  Currently it will only read the files in the top level directory.  

Make sure to create a test for this new capability.  

Existing test class: EnhancedResourcesItemReaderTest.java

User the MapFileVisitor to traverse the directory

Make sure the test class is using the [TemporaryFolder](http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) feature of JUnit.

**Comment by gmarintes** [comment]
Working on this.
